<?xml version="1.0" encoding="utf-8"?>
<!-- This URDF was automatically created by SolidWorks to URDF Exporter! Originally created by Stephen Brawner (brawner@gmail.com) 
     Commit Version: 1.6.0-1-g15f4949  Build Version: 1.6.7594.29634
     For more information, please see http://wiki.ros.org/sw_urdf_exporter -->
<robot  name="bunker_description" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="r200_cam_rgb_px" value="0.005"/>
  <xacro:property name="r200_cam_rgb_py" value="0.018"/>
  <xacro:property name="r200_cam_rgb_pz" value="0.013"/>
  <xacro:property name="r200_cam_depth_offset" value="0.01"/>

  <xacro:arg name="camera_visual" default="false"/>
 
  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="robot_base" /> <!--original: base_link -->
    <origin xyz="0 0 0.355" rpy="0 0 0"/>
  </joint>

<!-- add frame stand joint 13Nov23 -->
  <joint name="baseto_framestand" type="fixed">
    <origin rpy="0 0 0" xyz="0.3 0 0"/>
    <parent link="robot_base"/>
    <child link="rbot_base2"/>
  </joint>
    
<!-- add maeterial colour for frame stand -->
  <material name="blue">
    <color rgba="0 0 0.8 1"/>
  </material>
  <material name="red">
    <color rgba="1 0 0 1"/>
  </material>
  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>

  <link name="rbot_base2">
    <visual>
      <geometry>
        <box size="0.045 0.09 0.03"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <material name="red"/>
    </visual>
  </link>
  <link name="servo_bottom2">
    <visual>
      <geometry>
        <cylinder length="0.25" radius="0.015"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <material name="green"/>
    </visual>
  </link> 

  <link name="up_mount2">
    <visual>
      <geometry>
        <box size="0.05 0.148 0.05"/>
      </geometry>
      <origin rpy="0 0. 0" xyz="0 0 0"/>
      <material name="blue"/>
    </visual>
  </link>  
    
 <joint name="base_to_Servo_B2" type="fixed">
    <parent link="rbot_base2"/>
    <child link="servo_bottom2"/>
    <origin xyz="0 0 0.14"/>
  </joint>
 <joint name="servo_bottom_to_up_mount2" type="fixed">
    <parent link="servo_bottom2"/>
    <child link="up_mount2"/>
    <origin xyz="0 0 0.15"/>
  </joint>
  <joint name="mount_to_camera2" type="fixed">
    <parent link="up_mount2"/>
    <child link="camera_link"/> <!-- original: base_link -->
    <origin rpy="0 0 0" xyz="0.03 -0.065 0.00"/>
  </joint>
    
      
  <link
    name="robot_base"> <!--original : base_link -->
     <inertial>
      <origin
        xyz="0.0212410555532523 0.00475458359568469 -0.127580557949736"
        rpy="0 0 0" />
      <mass
        value="0.0001" />
      <inertia
        ixx="0.607716166684979"
        ixy="1.92178193996147E-05"
        ixz="-0.036532069356182"
        iyy="1.70041426855404"
        iyz="2.16963122007266E-05"
        izz="1.84232351935185" />
    </inertial>
    <visual>
      <origin
        xyz="0.53 -0.392 -0.358"
        rpy="1.57 0 3.14" />
      <geometry>
        <mesh
          filename="package://bunker_description/meshes/BUNKER.STL" scale="0.001 0.001 0.001" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.5 0.5 0.5  1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0.53 -0.392 -0.358"
        rpy="1.57 0 3.14" />
      <geometry>
        <mesh
          filename="package://bunker_description/meshes/BUNKER.STL" scale="0.001 0.001 0.001" />
      </geometry>
    </collision>
  </link>
  <link
    name="wheel1_Link">
    <inertial>
      <origin
        xyz="0 -1.38777878078145E-17 -0.0719999999999999"
        rpy="0 0 0" />
      <mass
        value="0.0001" />
      <inertia
        ixx="0.000378440530116381"
        ixy="5.60822736805661E-21"
        ixz="3.04207802822425E-20"
        iyy="0.000378440530116381"
        iyz="-7.56626980356474E-21"
        izz="0.000710150518820894" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://bunker_description/meshes/wheel1_Link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 1 1 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://bunker_description/meshes/wheel1_Link.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="wheel1_joint"
    type="revolute">
    <origin
      xyz="0.44403 0.3495 -0.12853"
      rpy="1.5708 0 -3.1416" />
    <parent
      link="robot_base" /> <!--original base_link -->
    <child
      link="wheel1_Link" />
    <axis
      xyz="0 0 1" />
    <limit
      lower="-180"
      upper="180"
      effort="0"
      velocity="0" />
  </joint>
  <link
    name="wheel1.1_Link">
    <inertial>
      <origin
        xyz="-1.74279013442913E-08 5.87093572021469E-08 -0.0720000000000001"
        rpy="0 0 0" />
      <mass
        value="0.0001" />
      <inertia
        ixx="6.58750963981394E-05"
        ixy="-1.46558944641469E-09"
        ixz="-8.34967331718859E-12"
        iyy="6.58795984671517E-05"
        iyz="-2.4786046130206E-12"
        izz="0.000112721820875598" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://bunker_description/meshes/wheel1.1_Link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 1 1 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://bunker_description/meshes/wheel1.1_Link.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="wheel1.1_jont"
    type="revolute">
    <origin
      xyz="0.37551 0.3495 -0.22305"
      rpy="1.5708 0 -3.1416" />
    <parent
      link="robot_base" /> <!-- original : base_link -->
    <child
      link="wheel1.1_Link" />
    <axis
      xyz="0 0 1" />
    <limit
      lower="-180"
      upper="180"
      effort="0"
      velocity="0" />
  </joint>
  <link
    name="wheel1.2_Link">
    <inertial>
      <origin
        xyz="1.66533453693773E-16 4.16333634234434E-17 -0.0720000000000002"
        rpy="0 0 0" />
      <mass
        value="0.0001" />
      <inertia
        ixx="0.000179574259018481"
        ixy="1.15789498120549E-20"
        ixz="1.3563351843978E-21"
        iyy="0.000179574259018481"
        iyz="6.0369822309622E-23"
        izz="0.000332594534732139" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://bunker_description/meshes/wheel1.2_Link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 1 1 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://bunker_description/meshes/wheel1.2_Link.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="wheel1.2_joint"
    type="revolute">
    <origin
      xyz="0.29039 0.3495 -0.28104"
      rpy="1.5708 0 -3.1416" />
    <parent
      link="robot_base" /> <!-- original : base_link -->
    <child
      link="wheel1.2_Link" />
    <axis
      xyz="0 0 1" />
    <limit
      lower="-180"
      upper="180"
      effort="0"
      velocity="0" />
  </joint>
  <link
    name="wheel1.3_Link">
    <inertial>
      <origin
        xyz="3.44025652177504E-05 -2.66346274915008E-05 -0.0701504149473696"
        rpy="0 0 0" />
      <mass
        value="0.0001" />
      <inertia
        ixx="0.000105254202004996"
        ixy="1.32328029886322E-08"
        ixz="3.84294589102693E-11"
        iyy="0.000105248656147198"
        iyz="-1.41155611914915E-11"
        izz="0.000173280771745758" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://bunker_description/meshes/wheel1.3_Link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 1 1 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://bunker_description/meshes/wheel1.3_Link.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="wheel1.3_joint"
    type="revolute">
    <origin
      xyz="0.29603 0.3495 -0.087"
      rpy="1.5708 0 -3.1416" />
    <parent
      link="robot_base" /> <!-- original : base_link -->
    <child
      link="wheel1.3_Link" />
    <axis
      xyz="0 0 -1" />
    <limit
      lower="-180"
      upper="180"
      effort="0"
      velocity="0" />
  </joint>
  <link
    name="wheel2_Link">
    <inertial>
      <origin
        xyz="-1.66533453693773E-16 0 0.072"
        rpy="0 0 0" />
      <mass
        value="0.0001" />
      <inertia
        ixx="0.000378440530116381"
        ixy="3.37302217863781E-21"
        ixz="2.71827270955143E-20"
        iyy="0.000378440530116381"
        iyz="-7.32821644893157E-21"
        izz="0.000710150518820894" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://bunker_description/meshes/wheel2_Link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 1 1 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://bunker_description/meshes/wheel2_Link.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="wheel2_joint"
    type="revolute">
    <origin
      xyz="0.44403 -0.3495 -0.12853"
      rpy="1.5708 0 -3.1416" />
    <parent
      link="robot_base" /> <!-- original : base_link -->
    <child
      link="wheel2_Link" />
    <axis
      xyz="0 0 -1" />
    <limit
      lower="-180"
      upper="180"
      effort="0"
      velocity="0" />
  </joint>
  <link
    name="wheel2.1_Link">
    <inertial>
      <origin
        xyz="-1.74279017328693E-08 5.87093572160247E-08 0.0720000000000002"
        rpy="0 0 0" />
      <mass
        value="0.0001" />
      <inertia
        ixx="6.58750963981394E-05"
        ixy="-1.46558944642761E-09"
        ixz="-8.34967332343028E-12"
        iyy="6.58795984671517E-05"
        iyz="-2.47860459929511E-12"
        izz="0.000112721820875598" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://bunker_description/meshes/wheel2.1_Link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 1 1 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://bunker_description/meshes/wheel2.1_Link.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="wheel2.1_joint"
    type="revolute">
    <origin
      xyz="0.37551 -0.3495 -0.22305"
      rpy="1.5708 0 -3.1416" />
    <parent
      link="robot_base" /> <!-- original : base_link -->
    <child
      link="wheel2.1_Link" />
    <axis
      xyz="0 0 -1" />
    <limit
      lower="-180"
      upper="180"
      effort="0"
      velocity="0" />
  </joint>
  <link
    name="wheel2.2_Link">
    <inertial>
      <origin
        xyz="-1.38777878078145E-16 -4.85722573273506E-17 0.0720000000000003"
        rpy="0 0 0" />
      <mass
        value="0.0001" />
      <inertia
        ixx="0.00017957425901848"
        ixy="6.28960386226657E-21"
        ixz="2.14010788664762E-21"
        iyy="0.00017957425901848"
        iyz="1.27709655724716E-22"
        izz="0.000332594534732139" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://bunker_description/meshes/wheel2.2_Link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 1 1 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://bunker_description/meshes/wheel2.2_Link.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="wheel2.2_joint"
    type="revolute">
    <origin
      xyz="0.29039 -0.3495 -0.28104"
      rpy="1.5708 0 -3.1416" />
    <parent
      link="robot_base" /> <!-- original : base_link -->
    <child
      link="wheel2.2_Link" />
    <axis
      xyz="0 0 -1" />
    <limit
      lower="-180"
      upper="180"
      effort="0"
      velocity="0" />
  </joint>
  <link
    name="wheel2.3_Link">
    <inertial>
      <origin
        xyz="3.51083051564616E-05 -2.7181014665284E-05 0.0709276770204769"
        rpy="0 0 0" />
      <mass
        value="0.0001" />
      <inertia
        ixx="0.000105035118852508"
        ixy="1.32328029886296E-08"
        ixz="3.84294589110161E-11"
        iyy="0.00010502957299471"
        iyz="-1.41155611875745E-11"
        izz="0.00017298179736849" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://bunker_description/meshes/wheel2.3_Link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 1 1 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://bunker_description/meshes/wheel2.3_Link.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="wheel2.3_joint"
    type="revolute">
    <origin
      xyz="0.29603 -0.3495 -0.087"
      rpy="1.5708 0 -3.1416" />
    <parent
      link="robot_base" /> <!-- original : base_link -->
    <child
      link="wheel2.3_Link" />
    <axis
      xyz="0 0 1" />
    <limit
      lower="-180"
      upper="180"
      effort="0"
      velocity="0" />
  </joint>
  <link
    name="wheel3_Link">
    <inertial>
      <origin
        xyz="-1.5143569731535E-10 7.07767178198537E-16 -0.0246054820762604"
        rpy="0 0 0" />
      <mass
        value="0.0001" />
      <inertia
        ixx="0.00232456013775523"
        ixy="-1.61343020248111E-09"
        ixz="-4.5670735364335E-13"
        iyy="0.00232456564213727"
        iyz="-1.36036258272812E-18"
        izz="0.00308347787030649" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://bunker_description/meshes/wheel3_Link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 1 1 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://bunker_description/meshes/wheel3_Link.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="wheel3_joint"
    type="revolute">
    <origin
      xyz="-0.38871 0.295 -0.19381"
      rpy="1.5708 0 -3.1416" />
    <parent
      link="robot_base" /> <!-- original : base_link -->
    <child
      link="wheel3_Link" />
    <axis
      xyz="0 0 -1" />
    <limit
      lower="-180"
      upper="180"
      effort="0"
      velocity="0" />
  </joint>
  <link
    name="wheel3.1_Link">
    <inertial>
      <origin
        xyz="5.55111512312578E-17 5.55111512312578E-17 -0.0720000000000002"
        rpy="0 0 0" />
      <mass
        value="0.0001" />
      <inertia
        ixx="0.000179574259018481"
        ixy="-1.73824343982442E-20"
        ixz="-2.53159654382751E-21"
        iyy="0.000179574259018481"
        iyz="-3.13741449878515E-21"
        izz="0.000332594534732139" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://bunker_description/meshes/wheel3.1_Link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 1 1 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://bunker_description/meshes/wheel3.1_Link.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="wheel3.1_joint"
    type="revolute">
    <origin
      xyz="-0.23111 0.3495 -0.27671"
      rpy="1.5708 0 -3.1416" />
    <parent
      link="robot_base" /> <!-- original : base_link -->
    <child
      link="wheel3.1_Link" />
    <axis
      xyz="0 0 1" />
    <limit
      lower="-180"
      upper="180"
      effort="0"
      velocity="0" />
  </joint>
  <link
    name="wheel3.2_Link">
    <inertial>
      <origin
        xyz="7.58128369110489E-17 7.63278329429795E-17 -0.0720000000000003"
        rpy="0 0 0" />
      <mass
        value="0.0001" />
      <inertia
        ixx="0.00017957425901848"
        ixy="9.82929052458426E-22"
        ixz="1.10990388135291E-21"
        iyy="0.00017957425901848"
        iyz="-4.81322327079121E-21"
        izz="0.000332594534732139" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://bunker_description/meshes/wheel3.2_Link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 1 1 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://bunker_description/meshes/wheel3.2_Link.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="wheel3.2_joint"
    type="revolute">
    <origin
      xyz="0.043885 0.3495 -0.27671"
      rpy="1.5708 0 -3.1416" />
    <parent
      link="robot_base" /> <!-- original : base_link -->
    <child
      link="wheel3.2_Link" />
    <axis
      xyz="0 0 1" />
    <limit
      lower="-180"
      upper="180"
      effort="0"
      velocity="0" />
  </joint>
  <link
    name="wheel3.3_Link">
    <inertial>
      <origin
        xyz="1.37732703020532E-08 -5.29206664124648E-05 -0.0701501700151683"
        rpy="0 0 0" />
      <mass
        value="0.0001" />
      <inertia
        ixx="0.000105264944409738"
        ixy="7.98231761628902E-12"
        ixz="6.80400273605472E-11"
        iyy="0.000105238344260685"
        iyz="-2.72106317781962E-11"
        izz="0.000173281039335396" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://bunker_description/meshes/wheel3.3_Link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 1 1 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://bunker_description/meshes/wheel3.3_Link.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="wheel3.3_joint"
    type="revolute">
    <origin
      xyz="-0.28597 0.3495 -0.087"
      rpy="1.5708 0 -3.1416" />
    <parent
      link="robot_base" /> <!-- original : base_link -->
    <child
      link="wheel3.3_Link" />
    <axis
      xyz="0 0 -1" />
    <limit
      lower="-180"
      upper="180"
      effort="0"
      velocity="0" />
  </joint>
  <link
    name="wheel4_Link">
    <inertial>
      <origin
        xyz="5.55111512312578E-17 1.51436273243544E-10 0.0245928853369881"
        rpy="0 0 0" />
      <mass
        value="0.0001" />
      <inertia
        ixx="0.00232456564213727"
        ixy="-1.6134302023684E-09"
        ixz="-3.67391703208082E-19"
        iyy="0.00232456013775523"
        iyz="-4.56707494796216E-13"
        izz="0.00308347787030649" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://bunker_description/meshes/wheel4_Link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 1 1 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://bunker_description/meshes/wheel4_Link.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="wheel4_joint"
    type="revolute">
    <origin
      xyz="-0.38871 -0.295 -0.19381"
      rpy="1.5708 0 -3.1416" />
    <parent
      link="robot_base" /> <!-- original : base_link -->
    <child
      link="wheel4_Link" />
    <axis
      xyz="0 0 1" />
    <limit
      lower="-180"
      upper="180"
      effort="0"
      velocity="0" />
  </joint>
  <link
    name="wheel4.1_Link">
    <inertial>
      <origin
        xyz="-1.11022302462516E-16 -5.55111512312578E-17 0.0720000000000002"
        rpy="0 0 0" />
      <mass
        value="0.0001" />
      <inertia
        ixx="0.000179574259018481"
        ixy="-7.93399024302093E-21"
        ixz="-2.13342044570487E-21"
        iyy="0.000179574259018481"
        iyz="-3.23624373974149E-21"
        izz="0.000332594534732139" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://bunker_description/meshes/wheel4.1_Link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 1 1 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://bunker_description/meshes/wheel4.1_Link.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="wheel4.1_joint"
    type="revolute">
    <origin
      xyz="-0.23111 -0.3495 -0.27671"
      rpy="1.5708 0 -3.1416" />
    <parent
      link="robot_base" /> <!-- original : base_link -->
    <child
      link="wheel4.1_Link" />
    <axis
      xyz="0 0 -1" />
    <limit
      lower="-180"
      upper="180"
      effort="0"
      velocity="0" />
  </joint>
  <link
    name="wheel4.2_Link">
    <inertial>
      <origin
        xyz="-7.64498056873841E-17 -4.85722573273506E-17 0.0720000000000004"
        rpy="0 0 0" />
      <mass
        value="0.0001" />
      <inertia
        ixx="0.00017957425901848"
        ixy="6.3005828905746E-22"
        ixz="1.1753358195074E-22"
        iyy="0.00017957425901848"
        iyz="-3.27347099653111E-21"
        izz="0.000332594534732139" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://bunker_description/meshes/wheel4.2_Link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 1 1 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://bunker_description/meshes/wheel4.2_Link.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="wheel4.2_joint"
    type="revolute">
    <origin
      xyz="0.043885 -0.3495 -0.27671"
      rpy="1.5708 0 -3.1416" />
    <parent
      link="robot_base" /> <!-- original : base_link -->
    <child
      link="wheel4.2_Link" />
    <axis
      xyz="0 0 -1" />
    <limit
      lower="-180"
      upper="180"
      effort="0"
      velocity="0" />
  </joint>
  <link
    name="wheel4.3_Link">
    <inertial>
      <origin
        xyz="1.37732700244975E-08 -5.29206664124926E-05 0.0701152686893121"
        rpy="0 0 0" />
      <mass
        value="0.0001" />
      <inertia
        ixx="0.000105264944409738"
        ixy="7.98231761858719E-12"
        ixz="6.80400273764357E-11"
        iyy="0.000105238344260685"
        iyz="-2.72106317797361E-11"
        izz="0.000173281039335396" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://bunker_description/meshes/wheel4.3_Link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 1 1 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://bunker_description/meshes/wheel4.3_Link.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="wheel4.3_joint"
    type="revolute">
    <origin
      xyz="-0.28597 -0.3495 -0.087"
      rpy="1.5708 0 -3.1416" />
    <parent
      link="robot_base" /> <!-- original : base_link -->
    <child
      link="wheel4.3_Link" />
    <axis
      xyz="0 0 1" />
    <limit
      lower="-180"
      upper="180"
      effort="0"
      velocity="0" />
  </joint>


  <!-- add joint frame stand 13 Nov 23-->  
<!--  <joint name="baseto_framestand" type="fixed">
    <origin rpy="0 0 0" xyz="0.3 0 0"/>
    <parent link="robot_base"/>
    <child link="rbot_base2"/>
  </joint> -->

<!-- original joint r200 camera to bunker -->
<!--  <joint name="camera_joint" type="fixed">
    <origin xyz="0.064 -0.065 0.094" rpy="0 0 0"/>
    <parent link="robot_base"/> <!-original base link -> 
    <child link="camera_link"/>
  </joint> -->

  <link name="camera_link">
    <visual>
     <origin xyz="0 0 0" rpy="1.57 0 1.57"/>
      <geometry>
       <mesh filename="package://bunker_description/meshes/sensors/r200.dae" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0.003 0.065 0.007" rpy="0 0 0"/>
      <geometry>
        <box size="0.012 0.132 0.020"/>
      </geometry>
    </collision>

    <!-- This inertial field needs doesn't contain reliable data!! -->
<!--   <inertial>
      <mass value="0.564" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.003881243" ixy="0.0" ixz="0.0"
               iyy="0.000498940" iyz="0.0"
               izz="0.003879257" />
    </inertial>-->
  </link>  

  <joint name="camera_rgb_joint" type="fixed">
    <origin xyz="${r200_cam_rgb_px} ${r200_cam_rgb_py} ${r200_cam_rgb_pz}" rpy="0 0 0"/>
    <parent link="camera_link"/>
    <child link="camera_rgb_frame"/>
  </joint>
  <link name="camera_rgb_frame"/>

  <joint name="camera_rgb_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="-1.57 0 -1.57"/>
    <parent link="camera_rgb_frame"/>
    <child link="camera_rgb_optical_frame"/>
  </joint>
  <link name="camera_rgb_optical_frame"/>

  <joint name="camera_depth_joint" type="fixed">
    <origin xyz="${r200_cam_rgb_px} ${r200_cam_rgb_py + r200_cam_depth_offset} ${r200_cam_rgb_pz}" rpy="0 0 0"/>
    <parent link="camera_link"/>
    <child link="camera_depth_frame"/>
  </joint>
  <link name="camera_depth_frame"/>

  <joint name="camera_depth_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="-1.57 0 -1.57"/>
    <parent link="camera_depth_frame"/>
    <child link="camera_depth_optical_frame"/>
  </joint>
  <link name="camera_depth_optical_frame"/>

  <!-- from waffle models sdf from pkg=turtlebot3_simulation-->
  <!-- <link name="image">
    <inertial>
      <pose>-0.069 0 0.104 0 0 0</pose>
      <inertia>
        <ixx>0.001</ixx>
        <ixy>0.000</ixy>
        <ixz>0.000</ixz>
        <iyy>0.001</iyy>
        <iyz>0.000</iyz>
        <izz>0.001</izz>
      </inertia>
      <mass>0.035</mass>
    </inertial>

    <collision name="image_collision">
      <pose>-0.069 0 0.104 0 0 0</pose>
      <geometry>
        <box>
          <size>0.008 0.130 0.022</size>
        </box>
      </geometry>
    </collision>

    <sensor name="intel_realsense_r200" type="camera">
      <always_on>1</always_on>
      <visualize>0</visualize>
      <update_rate>30</update_rate>
      <pose>0.064 -0.047 0.107 0 0 0</pose>
      <camera>
        <horizontal_fov>1.02974</horizontal_fov>
        <image>
          <width>1920</width>
          <height>1080</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.02</near>
          <far>300</far>
        </clip>
      </camera>
    </sensor>
  </link> -->


  <!-- /////////////////////////////////   gazebo color   ////////////////////////////////////// -->

 <gazebo reference="robot_base"> <!--base_link-->
     <material>Gazebo/Gray</material>
  </gazebo>

  <!-- <gazebo>
    <plugin name="object_controller" filename="libgazebo_ros_planar_move.so">
      <commandTopic>cmd_vel</commandTopic>
      <odometryTopic>odom</odometryTopic>
      <odometryFrame>odom</odometryFrame>
      <odometryRate>20.0</odometryRate>
      <robotBaseFrame>base_link</robotBaseFrame>
    </plugin>
  </gazebo> -->
  <gazebo>
    <plugin name="object_controller" filename="libgazebo_ros_planar_move.so">
      <commandTopic>smoother_cmd_vel</commandTopic> <!-- original cmd_vel -->
      <odometryTopic>odom</odometryTopic>
      <odometryFrame>odom</odometryFrame>
      <odometryRate>20.0</odometryRate>
      <leftFrontJoint>wheel1_2_joint</leftFrontJoint>
      <rightFrontJoint>wheel2_2_joint</rightFrontJoint>
      <leftRearJoint>wheel3_1_joint</leftRearJoint>
      <rightRearJoint>wheel4_1_joint</rightRearJoint>
      <!-- <robotBaseFrame>base_link</robotBaseFrame> #original -->
      <robotBaseFrame>robot_base</robotBaseFrame>
    </plugin>
  </gazebo>
  
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <!-- <robotNamespace>/</robotNamespace> -->
      <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
      <legacyModeNS>true</legacyModeNS>
    </plugin>
  </gazebo>

  <gazebo reference="camera_rgb_frame">
    <sensor type="depth" name="realsense_R200">
      <always_on>true</always_on>
      <visualize>$(arg camera_visual)</visualize>
      <camera>
          <horizontal_fov>1.3439</horizontal_fov>
          <image>
              <width>1920</width>
              <height>1080</height>
              <format>R8G8B8</format>
          </image>
          <depth_camera></depth_camera>
          <clip>
              <near>0.03</near>
              <far>100</far>
          </clip>
      </camera>
      <plugin name="camera_controller" filename="libgazebo_ros_openni_kinect.so">
        <baseline>0.2</baseline>
        <alwaysOn>true</alwaysOn>
        <updateRate>30.0</updateRate>
        <cameraName>camera</cameraName>
        <frameName>camera_rgb_optical_frame</frameName>
        <imageTopicName>rgb/image_raw</imageTopicName>
        <depthImageTopicName>depth/image_raw</depthImageTopicName>
        <pointCloudTopicName>depth/points</pointCloudTopicName>
        <cameraInfoTopicName>rgb/camera_info</cameraInfoTopicName>
        <depthImageCameraInfoTopicName>depth/camera_info</depthImageCameraInfoTopicName>
        <pointCloudCutoff>0.4</pointCloudCutoff>
            <hackBaseline>0.07</hackBaseline>
            <distortionK1>0.0</distortionK1>
            <distortionK2>0.0</distortionK2>
            <distortionK3>0.0</distortionK3>
            <distortionT1>0.0</distortionT1>
            <distortionT2>0.0</distortionT2>
        <CxPrime>0.0</CxPrime>
        <Cx>0.0</Cx>
        <Cy>0.0</Cy>
        <focalLength>0</focalLength>
        <hackBaseline>0</hackBaseline>
      </plugin>
    </sensor>
  </gazebo>
    
  <gazebo>
    <plugin name="gps_controller" filename="libhector_gazebo_ros_gps.so">
      <!--<robotNamespace>$(arg robot_namespace)</robotNamespace> -->
      <updateRate>40</updateRate>
      <bodyName>robot_base</bodyName>
      <frameId>robot_base</frameId>
      <topicName>navsat/fix</topicName>
      <velocityTopicName>navsat/vel</velocityTopicName>
      <referenceLatitude>49.9</referenceLatitude>
      <referenceLongitude>8.9</referenceLongitude>
      <referenceHeading>0</referenceHeading>
      <referenceAltitude>0</referenceAltitude>
      <drift>0.0001 0.0001 0.0001</drift>
    </plugin>
  </gazebo>

</robot>
